<div class="row-fluid">
    <div class="span3">
        <div class="well sidebar-nav">
            <ul class="nav nav-list">
                <li class="nav-header">Contacts</li>
                <li><a href="/contacts">List</a></li>
                <li class="active"><a href="/contacts/add">Add</a></li>
            </ul>
        </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
        <div class="row-fluid">
            <div class="span12">
                <form class="form-horizontal">
                    <div class="control-group">
                        <label class="control-label" for="inputName">Name</label>
                        <div class="controls">
                            <input type="text" id="inputName" placeholder="Name">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputEmail">Email</label>
                        <div class="controls">
                            <input type="text" id="inputEmail" placeholder="Email">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="inputPhoneNumber">Phone Number</label>
                        <div class="controls">
                            <input type="text" id="inputPhoneNumber" placeholder="Phone Number">
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn">Add</button>
                        </div>
                    </div>
                </form>
            </div><!--/span-->
        </div><!--/row-->
    </div><!--/span-->
</div><!--/row-->