<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Gather action="/call/booked?call_id=<?php echo $this->callId; ?>" numDigits="1">
        <Say>We are happy to hear that you booked a stay with us.</Say>
        <Say>On a scale of 1 to 5 please rate your stay.</Say>
        <Say>1 being the lowest and 5 being the highest.</Say>
    </Gather>
    <Say>Sorry I didn't get your response.</Say>
    <Redirect>/call/booked</Redirect>
</Response>
