<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Gather action="/call/index" numDigits="1">
        <Say>Thank you for using TravelNet Solutions.</Say>
        <Say>We are calling you today in regards to your previous inquery of booking a stay with us.</Say>
        <Say>Press 1 if you completed your booking.</Say>
        <Say>Press 2 if you decided to cancel.</Say>
    </Gather>
    <Say>Sorry I didn't get your response.</Say>
    <Redirect>/call/index</Redirect>
</Response>
