<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Gather action="/call/step2" numDigits="1">
        <Say>Thank you for using TravelNet Solutions.</Say>
        <Say>We are calling you today regarding your recent visit.</Say>
        <Say>Press 1 if you enjoyed your stay.</Say>
        <Say>Press 2 if you were unsatisfied with your stay.</Say>
        <Say>PRess 3 if you did not stay with us</Say>
    </Gather>
    <Say>Sorry I didn't get your response.</Say>
    <Redirect>/call/index</Redirect>
</Response>
