<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Gather action="/call/noBooking?call_id=<?php echo $this->callId; ?>" numDigits="1">
        <Say>We are sorry to hear that you decided not to book your stay with us.</Say>
        <Say>Please let us know the reason why you decided not to book with us.</Say>
        <Say>Press 1 if you decided to book with another location.</Say>
        <Say>Press 2 if you decided to book at a later time.</Say>
        <Say>Press 3 for financial reasons</Say>
        <Say>Press 4 for personal reasons</Say>
        <Say>Press 5 for other</Say>
    </Gather>
    <Say>Sorry I didn't get your response.</Say>
    <Redirect>/call/noBooking</Redirect>
</Response>
