<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Gather action="/call/noBooking?call_id=<?php echo $this->callId; ?>" numDigits="1">
        <Say>We are sorry to hear that you decided not to book your stay with us.</Say>
        <Say>Please let us know the reason why you decided not to book with us.</Say>
        <?php foreach($this->reasons as $i => $reason):?>
        <Say>Press <?php echo $reason->id;?> <?php echo $reason->reason; ?>.</Say>
        <?php endforeach; ?>
    </Gather>
    <Say>Sorry I didn't get your response.</Say>
    <Redirect>/call/noBooking</Redirect>
</Response>
