<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Gather action="/call/booked?call_id=<?php echo $this->callId; ?>" numDigits="1">
        <Say>Based on your original property we have determined that you may be also interested in the following.</Say>
        <Say>Based on your selection we will automatically connect you with the property.</Say>
        <?php foreach($this->properties as $i => $property):?>
        <Say>Press <?php echo $i; ?> to connect to <?php echo $property->name; ?></Say>
        <?php endforeach; ?>
    </Gather>
    <Say>Sorry I didn't get your response.</Say>
    <Redirect>/call/booked</Redirect>
</Response>
