<div class="row-fluid">
    <div class="span3">
        <div class="well sidebar-nav">
            <ul class="nav nav-list">
                <li class="nav-header">Properties</li>
                <li class="active"><a href="/properties">List</a></li>
                <li><a href="/properties/add">Add</a></li>
            </ul>
        </div><!--/.well -->
    </div><!--/span-->
    <div class="span9">
        <div class="row-fluid">
            <div class="span12">
                <table class="table">
                    <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Phone</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->properties as $property): ?>
                        <tr>
                            <td><?php echo $this->escape($property->id); ?></td>
                            <td><?php echo $this->escape($property->name); ?></td>
                            <td>
                                <?php echo $this->escape($property->address); ?><br>
                                <?php echo $this->escape($property->city); ?>,
                                <?php echo $this->escape($property->state); ?>
                                <?php echo $this->escape($property->postal_code); ?>
                            </td>
                            <td><?php echo $this->escape($property->phone); ?></td>
                            <td><a href="/properties/edit/<?php echo $this->escape($property->id); ?>">Edit</a>
                                | <a href="/properties/delete/<?php echo $this->escape($property->id); ?>">delete</a></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div><!--/span-->
        </div><!--/row-->
    </div><!--/span-->
</div><!--/row-->